FROM node:22.20-bookworm-slim
RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1

WORKDIR /app
COPY . /app

RUN pnpm install
RUN pnpm run build:orchestrator

# Ensure we use the PORT variable from Railway
CMD ["sh", "-c", "pnpm run start:prod:orchestrator"]
